# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np

arr=np.random.random((3,3,3))
print(arr)

[[[0.76608378 0.47932732 0.03274448]
  [0.5586764  0.84941682 0.60253779]
  [0.03295641 0.48547595 0.69319694]]

 [[0.78890539 0.78175816 0.99493349]
  [0.26691514 0.09302503 0.19341202]
  [0.35727908 0.1355413  0.23620679]]

 [[0.5005846  0.21900288 0.12800981]
  [0.97963497 0.10132726 0.62378792]
  [0.53720129 0.86241453 0.80968624]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
mat=np.diag(1+np.arange(4),k=-1)
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
mat=np.zeros((8,8),dtype=int)
mat[1::2,::2]=1
mat[::2,1::2]=1
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
mat=np.random.random((5,5))
print("Before Normalization\n")
print(mat)
mat_max,mat_min=mat.max(),mat.min()
mat=(mat-mat_min)/(mat_max-mat_min)
print("\nAfter Normalization\n\n",mat)

Before Normalization

[[0.6818235  0.70721857 0.11250979 0.4663252  0.44322914]
 [0.89825366 0.4731691  0.94802815 0.74572398 0.59558579]
 [0.97797823 0.90283072 0.82376351 0.67567271 0.24684164]
 [0.89627905 0.38604228 0.13002538 0.52879271 0.03093919]
 [0.33460545 0.71443676 0.87823668 0.9620208  0.33888994]]

After Normalization

 [[0.6872835  0.71409873 0.08613224 0.45973395 0.4353463 ]
 [0.91581702 0.46696059 0.96837502 0.75475747 0.59622315]
 [1.         0.92065003 0.83716117 0.68078874 0.22797628]
 [0.91373198 0.37496141 0.10462735 0.52569481 0.        ]
 [0.32064808 0.72172058 0.89468063 0.98315018 0.32517218]]


# 5. How to find common values between two arrays?

In [5]:
arr1=np.array([1,2,3,4,5])
print("Array 1:",arr1)
arr2=[5,10,15,2]
print("Array 2:",arr2)
print("The common values between two arrays are:")
print(np.intersect1d(arr1, arr2))

Array 1: [1 2 3 4 5]
Array 2: [5, 10, 15, 2]
The common values between two arrays are:
[2 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday=np.datetime64("today","D")-np.timedelta64(1,"D")
print("Yesterday:",yesterday)
today=np.datetime64("today","D")
print("Today:",today)
tomorrow=np.datetime64("today","D")+np.timedelta64(1,"D")
print("Tomorrow:",tomorrow)

Yesterday: 2020-07-26
Today: 2020-07-27
Tomorrow: 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [7]:
A=np.random.randint(0,2,2)
B=np.random.randint(0,2,2)
print("Array A:",A)
print("Array B:",B)
equal=np.allclose(A,B)
if(equal==True):
    print("Both the arrays are equal")
else:
    print("Both the arrays are different")

Array A: [1 1]
Array B: [0 0]
Both the arrays are different


# 8.Create random vector of size 10 and replace the maximum value by 0

In [8]:
vec=np.random.random(10)
print("Before replacing max value")
print(vec,"\n")
vec[vec.argmax()]=0
print("After replacing max value\n",vec)

Before replacing max value
[0.59860961 0.82244006 0.08358487 0.33058871 0.45986826 0.32650558
 0.74474898 0.83868951 0.09242036 0.71141657] 

After replacing max value
 [0.59860961 0.82244006 0.08358487 0.33058871 0.45986826 0.32650558
 0.74474898 0.         0.09242036 0.71141657]


# 9. How to print all the values of an array?

In [9]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# 10.Subtract the mean of each row of a matrix

In [10]:
mat=np.random.rand(3,5)
print("Original matrix:\n")
print(mat)
print("\nAfter subtraction of the mean of each row of the matrix:\n")
mat2=mat-mat.mean(axis=1,keepdims=True)
print(mat2)

Original matrix:

[[0.6004188  0.22449979 0.07964129 0.74412707 0.44117679]
 [0.48502813 0.94479638 0.85976237 0.69103165 0.3119741 ]
 [0.15756058 0.89900635 0.09205436 0.7847021  0.30373183]]

After subtraction of the mean of each row of the matrix:

[[ 0.18244605 -0.19347296 -0.33833146  0.32615432  0.02320405]
 [-0.17349039  0.28627786  0.20124384  0.03251312 -0.34654443]
 [-0.28985047  0.4515953  -0.35535668  0.33729106 -0.14367921]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [11]:
vec1=np.random.randint(10,30,4)
print(vec1)
vec2=[2,0,3,1]
vec1=vec1[vec2]+1
print(vec1)

[27 18 19 25]
[20 28 26 19]


# 12.How to get the diagonal of a dot product?

In [12]:
x=[[3,2],[1,4]]
y=[[2,2],[5,1]]
print("Dot product:\n",np.dot(x,y))
z=np.diag(np.dot(x,y))
print("Diagonal of a dot product:",z)

Dot product:
 [[16  8]
 [22  6]]
Diagonal of a dot product: [16  6]


# 13.How to find the most frequent value in an array?

In [13]:
arr=np.random.randint(0,10,50)
print(arr)
print("Most Frequent Value:",np.bincount(arr).argmax())

[6 3 8 2 8 9 4 1 0 9 3 3 3 2 5 8 2 5 4 4 4 2 9 2 5 6 2 0 6 3 9 4 1 2 1 5 9
 9 1 7 0 6 4 1 4 2 2 2 8 5]
Most Frequent Value: 2


# 14.How to get the n largest values of an array

In [14]:
arr=np.arange(10)
np.random.shuffle(arr)
print("Array:",arr)
n=3
print("The",n,"largest values of the array are:",arr[np.argsort(arr)[-n:]])

Array: [1 6 5 0 3 8 9 4 7 2]
The 3 largest values of the array are: [7 8 9]


# 15.How to create a record array from a regular array?

In [15]:
arr1=np.array([("Hi","Hello","Namaste"),("How","Are","You"),("I","Am","Fine")])
arr2=np.core.records.fromarrays(arr1.T,names='c1,c2,c3')
print("Regular Array:\n",arr1,"\n")
print("Record Array:\n",arr2)

Regular Array:
 [['Hi' 'Hello' 'Namaste']
 ['How' 'Are' 'You']
 ['I' 'Am' 'Fine']] 

Record Array:
 [('Hi', 'Hello', 'Namaste') ('How', 'Are', 'You') ('I', 'Am', 'Fine')]
